export const SEARCH = 'SEARCH_DATA';
export const SEARCH_DONE = 'SEARCH_DATA@@DONE';
export const SEARCH_ERRORS = 'SEARCH_DATA@@ERRORS';

export const SEARCH_CANCEL = 'SEARCH_CANCEL';
export const SEARCH_CANCEL_DONE = 'SEARCH_CANCEL@@DONE';
export const SEARCH_CANCEL_ERRORS = 'SEARCH_CANCEL@@ERRORS';

export const ON_NEXT = 'ON_NEXT';
